//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stein.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stein.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested application folder is not cached and could not be updated..
        /// </summary>
        public static string ApplicationFolderNotCached {
            get {
                return ResourceManager.GetString("ApplicationFolderNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle language:.
        /// </summary>
        public static string BundleLanguage {
            get {
                return ResourceManager.GetString("BundleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled, finishing current operation….
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed: {0}  Reinstalled: {1}  Uninstalled: {2}.
        /// </summary>
        public static string DidInstallXPrograms {
            get {
                return ResourceManager.GetString("DidInstallXPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable reboot after installation.
        /// </summary>
        public static string DisableReboot {
            get {
                return ResourceManager.GetString("DisableReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Folder.
        /// </summary>
        public static string EditFolder {
            get {
                return ResourceManager.GetString("EditFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity was not found..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ….
        /// </summary>
        public static string Hellip {
            get {
                return ResourceManager.GetString("Hellip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installer file at {0} was not found..
        /// </summary>
        public static string InstallerNotFound {
            get {
                return ResourceManager.GetString("InstallerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path of the installer is empty. The operation could not be executed..
        /// </summary>
        public static string InstallerPathIsEmpty {
            get {
                return ResourceManager.GetString("InstallerPathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing….
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install log.
        /// </summary>
        public static string InstallLog {
            get {
                return ResourceManager.GetString("InstallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should not be empty..
        /// </summary>
        public static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dialog found to display this DialogModel..
        /// </summary>
        public static string NoDialogExistsForDialogModel {
            get {
                return ResourceManager.GetString("NoDialogExistsForDialogModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string OneHourAgo {
            get {
                return ResourceManager.GetString("OneHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        public static string OneMinuteAgo {
            get {
                return ResourceManager.GetString("OneMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 second ago.
        /// </summary>
        public static string OneSecondAgo {
            get {
                return ResourceManager.GetString("OneSecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path should not be empty..
        /// </summary>
        public static string PathEmpty {
            get {
                return ResourceManager.GetString("PathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing….
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product code is empty. The operation could not be executed..
        /// </summary>
        public static string ProductCodeIsEmpty {
            get {
                return ResourceManager.GetString("ProductCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching installerfiles in {0} failed.
        ///{1}.
        /// </summary>
        public static string RefreshFailed {
            get {
                return ResourceManager.GetString("RefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        public static string Reinstall {
            get {
                return ResourceManager.GetString("Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstalling….
        /// </summary>
        public static string Reinstalling {
            get {
                return ResourceManager.GetString("Reinstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the configuration failed..
        /// </summary>
        public static string SaveConfigurationFailed {
            get {
                return ResourceManager.GetString("SaveConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected path is not valid..
        /// </summary>
        public static string SelectedPathNotValid {
            get {
                return ResourceManager.GetString("SelectedPathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No UI during install.
        /// </summary>
        public static string SilentInstall {
            get {
                return ResourceManager.GetString("SilentInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch theme.
        /// </summary>
        public static string SwitchTheme {
            get {
                return ResourceManager.GetString("SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling….
        /// </summary>
        public static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view for ViewModel type {0} is of wrong type {1}. Requested type was {2}..
        /// </summary>
        public static string ViewHasWrongTypeX {
            get {
                return ResourceManager.GetString("ViewHasWrongTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening the dialog failed. The dialog view is not a window..
        /// </summary>
        public static string ViewIsNoWindow {
            get {
                return ResourceManager.GetString("ViewIsNoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ViewModel is not supported. The operation could not be executed..
        /// </summary>
        public static string ViewModelNotSupported {
            get {
                return ResourceManager.GetString("ViewModelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string XHoursAgo {
            get {
                return ResourceManager.GetString("XHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installers failed..
        /// </summary>
        public static string XInstallersFailed {
            get {
                return ResourceManager.GetString("XInstallersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo {
            get {
                return ResourceManager.GetString("XMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo {
            get {
                return ResourceManager.GetString("XSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
